<?php
return array (
  'open_wap' => '0',
  'message_check_code' => '1',
  'smtp_server' => 'smtp.qq.com',
  'smtp_port' => '465',
  'smtp_ssl' => '1',
  'smtp_username' => '1651978720@qq.com',
  'smtp_password' => 'ezxdcdjpovnneadd',
  'admin_check_code' => '1',
  'weixin_appid' => '',
  'weixin_secret' => '',
  'message_send_mail' => '1',
  'message_send_to' => '1651978720@qq.com',
  'api_open' => '0',
  'api_auth' => '1',
  'api_appid' => '',
  'api_secret' => '',
  'baidu_zz_token' => '0rt0NnO57WAOEXMO',
  'baidu_xzh_appid' => '1632048184127937',
  'baidu_xzh_token' => 'Or3kttVfxdCPLCNS',
  'wap_domain' => '',
  'gzip' => '0',
  'smtp_username_test' => 'jsthree@dowv.com',
);